# Generated by Django 2.0.10 on 2019-02-10 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20190209_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='rank',
            field=models.IntegerField(unique=True),
        ),
    ]
