# Generated by Django 2.0.10 on 2019-02-11 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20190211_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='rank',
            field=models.IntegerField(),
        ),
    ]
