# Generated by Django 3.1.3 on 2020-11-22 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20201122_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decipher',
            name='clue_photo',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
