# Generated by Django 2.0.10 on 2019-02-05 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_post_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='name',
            new_name='tag',
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together={('tag', 'post')},
        ),
    ]
