# Generated by Django 2.0.10 on 2019-02-22 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20190212_1729'),
    ]

    operations = [
        migrations.CreateModel(
            name='Decipher',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('challenge', models.TextField()),
                ('clue', models.TextField()),
                ('code', models.CharField(max_length=20)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deciphers', to='blog.Post')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
