# Generated by Django 2.0.10 on 2019-02-22 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_decipher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decipher',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='decipher',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
