# Generated by Django 2.0.10 on 2019-02-22 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20190222_2340'),
    ]

    operations = [
        migrations.AddField(
            model_name='decipher',
            name='hidden_text',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
