# Generated by Django 2.0.10 on 2019-02-22 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_decipher_hidden_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decipher',
            name='name',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
