# Generated by Django 2.0.10 on 2019-03-06 09:37

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20190223_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decipher',
            name='challenge',
            field=tinymce.models.HTMLField(),
        ),
    ]
