personal_site:
  secret_key: (pfboe=(9khdb1#tas!u32q=7ecc%x4$2we%-_#fjot6=j#96#
  app_name: personal_site
  db:
    database: personalsite_db
    user: rtidev
    pass: password
    host: localhost
    port: 5432

personal_site_api:
  logger: PersonalSiteApiLogger
  tinymce:
    image_upload_endpoint: http://localhost:8000/api/v1/wysiwyg-image-upload

logging:
  version: 1 # required by dictConfig
  formatters:
    default:
      format: "%(asctime)s\t%(levelname)s\t%(name)s\t%(message)s"
  handlers:
    console:
      class: logging.StreamHandler
      formatter: default
      stream: ext://sys.stdout
    datestamp_logfile:
      level: INFO
      class: core.logger.DateStampedHandler
      filename_template: /home/rtidev/Projects/Others/logs/personal_site/%Y%m/%Y%m%d.api
    datestamp_chatbot_logfile:
      level: INFO
      class: core.logger.DateStampedHandler
      filename_template: /home/rtidev/Projects/Others/logs/personal_site/%Y%m/%Y%m%d.chatbot
    debug_log:
      level: DEBUG
      class: logging.handlers.TimedRotatingFileHandler
      formatter: default
      filename: /home/rtidev/Projects/Others/logs/personal_site/personal_site.log
      interval: 1
      backupCount: 7
      when: midnight
  loggers:
    personal_site_api.views:
      handlers: [console, debug_log]
      level: DEBUG
    PersonalSiteApiLogger:
      handlers: [datestamp_logfile]
      level: INFO
      propagate: True


  